version: '3.8'
services:
  web:
    build:
      context: .
      args:
        RAILS_ENV: development  # Ensure the Dockerfile builds with the right environment
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./db/sqlite:/var/lib/sqlite3
