name: Continuous Deployment

on:
  push:
    branches:
      - main  # Adjust to match your main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t myapp:${{ github.sha }} .
        docker push myapp:${{ github.sha }}

  deploy-to-aws:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.1.0'  # specify your version
    - name: Terraform Init and Apply
      run: |
        terraform init
        terraform apply -auto-approve
    - name: Deploy with Helm
      run: |
        helm upgrade --install my-ror-app ./helm/my-ror-app \
          --set image.repository=myapp \
          --set image.tag=${{ github.sha }} \
          --namespace default

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
