name: Continuous Deployment

on:
  push:
    branches:
      - main  # Adjust to match your main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my_ror_app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/my_ror_app:${{ github.sha }}

  deploy-to-aws:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Initialize Terraform
        run: terraform init
        working-directory: /home/aman/Desktop/DevOps\ A4/terraform-k8s   # Update this path
      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: /home/aman/Desktop/DevOps\ A4/terraform-k8s   # Update this path
      - name: Deploy with Helm
        run: |
          helm upgrade --install my-ror-app ./helm/my-ror-app \
            --set image.repository=myapp \
            --set image.tag=${{ github.sha }} \
            --namespace default

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
