name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # 1. Build Job
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        env:
          TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my_ror_app:$TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/my_ror_app:$TAG

  # 2. Unit Test Job
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Unit Tests
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/my_ror_app:${{ github.sha }} bundle install
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/my_ror_app:${{ github.sha }} bundle exec rspec

  # 3. Linter Job
  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y ruby rubocop

      - name: Run RuboCop
        run: |
          rubocop

  # 4. SAST Job
  sast:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Brakeman
        run: |
          brakeman

  # Optimization settings
  cache:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Ruby gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

  # Test results as artifacts
  upload-test-results:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: tmp/test-results

